### ISSUE TITLE
No InRelease file created

### ISSUE THREAD

**Issue by hemebond** [crewjam/s3repo#1]
There is no InRelease file created, only Release and Release.gpg. This seems to prevent it from being used as per the examples, instead throwing an error when used by apt-boto-s3 as the S3 apt transport.

**Comment by hemebond** [comment]
This is really an issue with apt-boto-s3 as it should just ignore the missing file.

**Comment by crewjam** [comment]
Hi James,

Thanks for the report. We didn't seem to need it in our use, but it looks easy enough to add if it helps others. Let me know if you think we should.

Cheers,

Ross
